name: Build

on: push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: "-Xmx768M"
    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK 21
      uses: actions/setup-java@v5
      with:
        java-version: 21
        distribution: temurin
    - name: Cache Maven packages
      uses: actions/cache@v6
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Install metafacture-core-snapshots
      run: |
        cd ..
        git clone https://github.com/metafacture/metafacture-core.git
        cd metafacture-core
        git checkout -b ddf031d1a5c792da16fc632354bded3bdcdda611
        git reset --hard ddf031d1a5c792da16fc632354bded3bdcdda611
        ./gradlew publishToMavenLocal
        cd -
    - name: Build with Maven
      run: |
        mvn clean install
        mvn editorconfig:check
    - name: Install the JSON Schema CLI
      uses: sourcemeta/jsonschema@v15.11.0
    - name: Validate Test Json Output with jsonschema
      run: |
        cd src/test/resources/
        bash validateJsonTestFiles.sh
        cd -
    - uses: sbt/setup-sbt@v1
      with:
        sbt-runner-version: 1.11.5
    - name: Cache SBT
      uses: actions/cache@v6
      with:
        path: |
          ~/.ivy2/cache
          ~/.sbt
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
    - name: Build and Test with play
      run: |
        cd web
        export JAVA_OPTS="--add-opens=java.base/sun.net.www.protocol.file=ALL-UNNAMED --add-exports=java.base/sun.net.www.protocol.file=ALL-UNNAMED"
        sbt -Djava.security.manager=allow clean
        sbt -Djava.security.manager=allow test
