name: Build

on: push
env:
  ACTIVATOR_VERSION: '1.3.10'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install metafacture-core snapshot
      run: |
        git clone https://github.com/metafacture/metafacture-core.git
        cd metafacture-core
        ./gradlew install
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Build with Maven
      run: mvn install
    - name: Build with play
      run: |
        cd web
        wget http://downloads.typesafe.com/typesafe-activator/${{env.ACTIVATOR_VERSION}}/typesafe-activator-${{env.ACTIVATOR_VERSION}}-minimal.zip
        unzip typesafe-activator-${{env.ACTIVATOR_VERSION}}-minimal.zip
        ./activator-${{env.ACTIVATOR_VERSION}}-minimal/bin/activator compile
        ./activator-${{env.ACTIVATOR_VERSION}}-minimal/bin/activator test
